# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gridot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gridot

  target 'gridotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gridotUITests' do
    # Pods for testing
  end

end
